---
- hosts: localhost

  tasks:

    - name: Build webserver container
      docker_image:
        name: webserver
        tag: 459
        path: ./python
        
    - name: Build mongo container
      docker_image:
        name: database
        tag: 459
        path: ./mongo

    - name: Create docker volume for the database
      docker_volume:
        name: mongo_data
      register: created_volume
        
    - name: Create docker volume for the database configuration
      docker_volume:
        name: mongo_config
        
    - name: Start mongo database container
      docker_container:
        name: database
        image: database:459
        volumes:
          - mongo_data:/data/db
          - mongo_config:/data/configdb

    - name: Wait for the database to start up
      wait_for:
        timeout: 10
      when: created_volume.changed
        
    - name: Create student collection
      shell: docker exec -i database mongo < mongo/CreateObjects.mongo
      when: created_volume.changed

    - name: Add sample data
      shell: docker exec -i database mongo < mongo/AddStudents.mongo
      when: created_volume.changed

    - name: Start python webserver container
      docker_container:
        name: webserver
        image: webserver:459
        links:
          - database:database
        published_ports:
          - 8080:5000
        env:
          DATABASE_NAME: database
